---

- name: debug hosts
  gather_facts: true
  hosts: all
  tasks:
  
    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
