---

- name: debug hosts
  gather_facts: true
  hosts: all
  tasks:
  
    - name: Display the config
      debug:
        msg: "The nodename is {{ ansible_nodename }} ."
        
    - name: Package installation
      yum:
      name:
        - vim
        - wget
      state: latest
        
